[project]
name = "next-best-fantastic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.50.0",
    "streamlit>=1.45.0",
]
